version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/hokiegeek/godemo
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
  release:
    docker:
      - image: goreleaser/goreleaser:v0.119.0
    working_directory: /go/src/github.com/hokiegeek/godemo
    steps:
      - checkout
      - run: goreleaser --config cmd/nx/.goreleaser.yml
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - release
