version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/hokiegeek/godemo
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
  release:
    docker:
      - image: goreleaser/goreleaser:v0.119.0
    working_directory: /go/src/github.com/hokiegeek/godemo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "92:47:93:9b:07:b1:22:63:9f:4b:55:85:88:4a:12:cb"
      - run: goreleaser
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - release:
          requires:
            - build
